name: tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - 'pypy3.9'
          - 'pypy3.10'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          pip install -r tests/config/requirements.txt
          pip install -e .
      - name: Set up Graylog
        run: |
          docker compose -f tests/config/docker-compose.yml up -d
          sleep 60
          ./tests/config/graylog-setup.sh
      - name: Run tests
        run: pytest -v --cov=pygelf
      - uses: coverallsapp/github-action@v2
        with:
          flag-name: ${{ matrix.python-version }}
          parallel: true
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Python dependencies
        run: pip install -r tests/config/requirements.txt
      - name: Run pylint
        run: pylint pygelf
  coverage:
    needs:
      - tests
    runs-on: ubuntu-22.04
    steps:
      - uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          fail-on-error: false
